export interface GCodeMetadata {
  tempoHoras: number; // Tempo em horas decimais (ex: 4.25)
  pesoGramas: number; // Peso do filamento em gramas (ex: 135.5)
  material?: string; // Tipo de filamento (PLA, PETG, ABS)
  alturaCamada?: number; // Altura de camada em mm (ex: 0.2)
  slicerDetectado: string; // Cura, PrusaSlicer, Bambu Studio
}

/**
 * Converte strings de tempo como "3h 45m 12s", "1d 2h 30m", "45m 10s", "14520s" ou segundos para horas decimais.
 */
function parseTimeStringToHours(timeStr: string): number {
  if (!timeStr) return 0;
  const str = timeStr.trim().toLowerCase();

  // If purely numeric, treat as seconds
  if (!isNaN(Number(str))) {
    return Number(str) / 3600;
  }

  let totalSeconds = 0;

  // Match days: e.g., 1d
  const daysMatch = str.match(/(\d+)\s*d/);
  if (daysMatch) totalSeconds += parseInt(daysMatch[1], 10) * 86400;

  // Match hours: e.g., 3h
  const hoursMatch = str.match(/(\d+)\s*h/);
  if (hoursMatch) totalSeconds += parseInt(hoursMatch[1], 10) * 3600;

  // Match minutes: e.g., 45m
  const minutesMatch = str.match(/(\d+)\s*m(?!s)/);
  if (minutesMatch) totalSeconds += parseInt(minutesMatch[1], 10) * 60;

  // Match seconds: e.g., 12s
  const secondsMatch = str.match(/(\d+)\s*s/);
  if (secondsMatch) totalSeconds += parseInt(secondsMatch[1], 10);

  if (totalSeconds > 0) {
    return totalSeconds / 3600;
  }

  return 0;
}

/**
 * Parser de Metadados G-code Server/Client Side
 */
export function parseGCodeContent(gcodeText: string): GCodeMetadata {
  if (!gcodeText) {
    throw new Error("Arquivo G-code vazio ou inválido.");
  }

  // Inspect first 100KB for comments
  const sample = gcodeText.slice(0, 100000);
  const lines = sample.split("\n");

  let slicerDetectado = "Fatiador Genérico";
  let tempoSegundos = 0;
  let tempoHoras = 0;
  let pesoGramas = 0;
  let material: string | undefined;
  let alturaCamada: number | undefined;

  // Detect Slicer Header
  if (sample.includes("generated by Cura") || sample.includes(";TIME:")) {
    slicerDetectado = "Ultimaker Cura";
  } else if (sample.includes("generated by PrusaSlicer") || sample.includes("PrusaSlicer")) {
    slicerDetectado = "PrusaSlicer";
  } else if (sample.includes("BambuStudio") || sample.includes("OrcaSlicer") || sample.includes("model printing time")) {
    slicerDetectado = "Bambu Studio / OrcaSlicer";
  }

  // 1. FORMATO CURA
  // ;TIME:14520
  // ;Filament weight: 135.6
  // ;Layer height: 0.2
  const curaTimeMatch = sample.match(/;TIME:(\d+)/i);
  if (curaTimeMatch) {
    tempoHoras = parseInt(curaTimeMatch[1], 10) / 3600;
  }

  const curaWeightMatch = sample.match(/;Filament weight:\s*([\d.]+)/i);
  if (curaWeightMatch) {
    pesoGramas = parseFloat(curaWeightMatch[1]);
  }

  const curaLayerMatch = sample.match(/;Layer height:\s*([\d.]+)/i);
  if (curaLayerMatch) {
    alturaCamada = parseFloat(curaLayerMatch[1]);
  }

  // 2. FORMATO PRUSASLICER / SUPERSLICER / SLIC3R
  // ; estimated printing time (normal mode) = 3h 45m 12s
  // ; filament used [g] = 124.5
  // ; filament_type = PLA
  // ; layer_height = 0.20
  const prusaTimeMatch = sample.match(/;\s*estimated printing time.*=\s*(.+)/i);
  if (prusaTimeMatch && !tempoHoras) {
    tempoHoras = parseTimeStringToHours(prusaTimeMatch[1]);
  }

  const prusaWeightMatch = sample.match(/;\s*filament used \[g\]\s*=\s*([\d.]+)/i);
  if (prusaWeightMatch && !pesoGramas) {
    pesoGramas = parseFloat(prusaWeightMatch[1]);
  }

  const prusaTypeMatch = sample.match(/;\s*filament_type\s*=\s*(.+)/i);
  if (prusaTypeMatch) {
    material = prusaTypeMatch[1].trim();
  }

  const prusaLayerMatch = sample.match(/;\s*layer_height\s*=\s*([\d.]+)/i);
  if (prusaLayerMatch && !alturaCamada) {
    alturaCamada = parseFloat(prusaLayerMatch[1]);
  }

  // 3. FORMATO BAMBU STUDIO / ORCASLICER
  // ; model printing time: 4h 12m 30s
  // ; total filament weight [g] : 156.4
  // ; filament_type = PETG
  const bambuTimeMatch = sample.match(/;\s*model printing time:\s*(.+)/i);
  if (bambuTimeMatch && !tempoHoras) {
    tempoHoras = parseTimeStringToHours(bambuTimeMatch[1]);
  }

  const bambuWeightMatch = sample.match(/;\s*total filament weight \[g\]\s*:\s*([\d.]+)/i);
  if (bambuWeightMatch && !pesoGramas) {
    pesoGramas = parseFloat(bambuWeightMatch[1]);
  }

  // Fallback: search length in meters if weight is 0 (ex: ;Filament used: 42.5m)
  if (pesoGramas === 0) {
    const lengthMatch = sample.match(/;Filament used:\s*([\d.]+)m/i) || sample.match(/;\s*filament used \[mm\]\s*=\s*([\d.]+)/i);
    if (lengthMatch) {
      const val = parseFloat(lengthMatch[1]);
      // If in mm, convert to meters
      const meters = sample.includes("[mm]") ? val / 1000 : val;
      // Approx 3g per meter for 1.75mm PLA/PETG
      pesoGramas = Math.round(meters * 3.0 * 10) / 10;
    }
  }

  // If no time or weight could be parsed
  if (tempoHoras === 0 && pesoGramas === 0) {
    throw new Error(
      "Não foi possível identificar o cabeçalho de comentários do G-code. Verifique se o arquivo possui metadados do fatiador."
    );
  }

  return {
    tempoHoras: Math.round(tempoHoras * 100) / 100,
    pesoGramas: Math.round(pesoGramas * 10) / 10,
    material,
    alturaCamada,
    slicerDetectado,
  };
}
